main: com.fren_gor.img.Main
version: 1.4.2
name: ImgPlacer
author: fren_gor

commands:
  placemap:
    description: Place an image
    permission: img.place
  imagedownload:
    description: Download an image
    permission: img.download
  reloadmaps:
    description: Reload
    permission: img.reload
  setimage:
    description: Set image to a player (Enter Spray Mode)
    permission: img.set
  removeimage:
    description: Remove image from a player (Exit Spray Mode)
    permission: img.remove

permissions:
  img.*:
    description: use the commands /placemap /reloadmaps /imagedownload
    default: op
    children:
      img.reload: true
      img.place: true
      img.download: true
      img.image: true
      img.remove: true
      img.set: true
      img.spray: true
  img.place:
    description: use the command /placemap
    default: op
  img.download:
    description: use the command /imagedownload
    default: op
  img.reload:
    description: use the command /reloadmaps
    default: op
  img.image:
    description: user can place all the maps
    default: op
  img.set:
    description: user can do /setimage
    default: op
  img.remove:
    description: user can do /removeimage
    default: op
  img.spray:
    description: user can place sprays
    default: op
